import React,{useEffect,useMemo,useState} from "react";
import {useLiveProducts} from "./LiveProductContext";
import {lookupClickProduct} from "./ClickGateway";
import "./credit-progress.css";
export type CreditPlan="48"|"CT1"|"CT2";
const DEFAULT_CPF="10304987506";
function entryNumber(v:string){return Number(v.replace(/\./g,"").replace(",",".").replace(/[^\d.-]/g,""))||0}
export function CrediarioSimulator(){
 const {products,addProduct}=useLiveProducts();const [code,setCode]=useState(""),[plan,setPlan]=useState<CreditPlan>("48"),[installments,setInstallments]=useState(10),[entry,setEntry]=useState(""),[voltage,setVoltage]=useState(""),[warranty,setWarranty]=useState(false),[cpf,setCpf]=useState(DEFAULT_CPF),[auxiliaryQuantity,setAuxiliaryQuantity]=useState(3),[loading,setLoading]=useState(false),[searching,setSearching]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<any>(null),[loadedProduct,setLoadedProduct]=useState<any>(null);
 const product=loadedProduct?.code===code.trim()?loadedProduct:useMemo(()=>products.find(p=>p.code===code.trim()),[products,code]);
 async function searchByCode(){const clean=code.trim();if(!clean)return;setSearching(true);try{const p=await lookupClickProduct(clean);if(!p.found)throw new Error("Produto não encontrado");setLoadedProduct(p);addProduct(p as any)}catch(e:any){setError(String(e.message||e))}finally{setSearching(false)}}
 async function simulate(){setError("");setResult(null);const cleanCode=code.trim(),cleanCpf=cpf.replace(/\D/g,"");if(!cleanCode){setError("Digite o código do produto.");return}if(cleanCpf.length!==11){setError("Digite um CPF com 11 números.");return}if((plan==="CT2"||plan==="48")&&entryNumber(entry)<=0){setError(`${plan} exige uma entrada maior que zero.`);return}setLoading(true);try{if(!product){const p=await lookupClickProduct(cleanCode);if(!p.found)throw new Error("Produto não encontrado");setLoadedProduct(p);addProduct(p as any)}const auxiliary=plan==="48"?[{code:"447157",quantity:1},{code:"801911",quantity:auxiliaryQuantity}]:[{code:"447164",quantity:1},{code:"801911",quantity:auxiliaryQuantity}];window.postMessage({source:"XVENDAS_CLICK",payload:{mode:"credit",productCode:cleanCode,plan,installments,entry:(plan==="CT2"||plan==="48")?entryNumber(entry):undefined,voltage:voltage||undefined,warranty,cpf:cleanCpf,auxiliaryQuantity,auxiliary}},window.location.origin);setResult({message:"Automação enviada para a nova aba da Plataforma Click."})}catch(e:any){setError(String(e.message||e))}finally{setLoading(false)}}
 return <section className="creditSimulator"><div className="creditHead"><div><span className="step">💳 Crediário</span><h3>Consultar pelo código do produto</h3></div><span>48 • CT1 • CT2</span></div><div className="creditGrid"><label>Código<input value={code} onChange={e=>setCode(e.target.value)}/><button type="button" onClick={searchByCode}>Buscar código</button></label><label>Plano<select value={plan} onChange={e=>setPlan(e.target.value as CreditPlan)}><option value="48">48</option><option value="CT1">CT1</option><option value="CT2">CT2</option></select></label><label>Parcelas<input type="number" value={installments} onChange={e=>setInstallments(Number(e.target.value))}/></label>{(plan==="CT2"||plan==="48")&&<label>Entrada<input value={entry} onChange={e=>setEntry(e.target.value)}/></label>}<label>Voltagem<select value={voltage} onChange={e=>setVoltage(e.target.value)}><option value="">Não se aplica</option><option value="110">110</option><option value="220">220</option></select></label><label>Garantia<select value={warranty?"yes":"no"} onChange={e=>setWarranty(e.target.value==="yes")}><option value="no">Sem garantia</option><option value="yes">12 meses</option></select></label><label>CPF<input value={cpf} onChange={e=>setCpf(e.target.value)}/></label></div><button className="primary creditAction" onClick={simulate} disabled={loading}>{loading?"Enviando...":"Consultar crediário"}</button>{error&&<div className="creditError">{error}</div>}{result&&<div className="creditResult"><p>{result.message}</p></div>}</section>;
}